plugins {
    id 'com.android.application'
}

android {
    namespace 'com.abhinav.aimlroadmap'
    compileSdk 36

    defaultConfig {
        applicationId 'com.abhinav.aimlroadmap'
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName '1.2'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
